# .shed.yml supporting automatic pushes.
owner: artbio
name: get_reference_fasta
description: Obtain reference genome sequence.
long_description: |
  Places the reference genome sequence in the current history.
  Useful for sharing purposes or tools that work directly on fasta files.
  This tool was originally developed by mvdbeek and is now maintained by artbio
categories:
  - Data Source
  - Fasta Manipulation
homepage_url: http://artbio.fr
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/master/tools/get_reference_fasta
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
  - testtoolshed
