# .shed.yml supporting automatic pushes.
owner: mvdbeek
name: get_reference_fasta
description: Obtain reference genome sequence.
long_description: |
  Places the reference genome sequence in the current history.
  Useful for sharing purposes or tools that work directly on fasta files.
categories:
  - Data Source
  - Fasta Manipulation
homepage_url: http://artbio.fr
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/master/tools/get_reference_fasta
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
  - testtoolshed
