# .shed.yml supporting automatic pushes.
owner: drosofff
name: msp_fasta_tabular_converter
description: various fasta to tabular conversions
long_description: |
  tool to convert fasta to tabular format or fasta to weighted fasta format and vice versa

categories:
  - Convert Formats
  - Fasta Manipulation

homepage_url: http://artbio.fr
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/master/tools/msp_fasta_tabular_converter
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
  - testtoolshed
  - toolshed
