# .shed.yml supporting automatic pushes.
owner: mvdbeek
name: deseq_normalization
description: Normalizes gene hitlists 
long_description: |
  Normalizes gene count lists using DESeq1 normalizeCounts() function.
categories:
  - RNA
homepage_url: http://drosophile.org/
remote_repository_url: https://bitbucket.org/drosofff/gedtools/
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
