# .shed.yml supporting automatic pushes.
owner: mvdbeek
name: deseq_normalization
description: Normalizes gene hitlists 
long_description: |
  Normalizes gene count lists using DESeq1 normalizeCounts() function.
categories:
  - RNA
homepage_url: http://artbio.fr
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/master/tools/deseq_normalization
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
  - testtoolshed
