# .shed.yml supporting automatic pushes.
owner: artbio
name: gsc_correlation
description: Compute single-cell paire-wise gene expressions correlations
long_description: |
  Compute single-cell paire-wise gene expressions correlations between genes or
  between genes and a signature of selected genes.
categories:
  - Transcriptomics
homepage_url: http://artbio.fr
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/master/tools/gsc_correlation
toolshed:
  - toolshed
