# .shed.yml supporting automatic pushes.
owner: artbio
name: gsc_filter_genes
description: Filter genes that are detected in less than a fraction of libraries in single cell RNAseq data
long_description:
categories:
  - Transcriptomics
homepage_url: http://artbio.fr
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/master/tools/gsc_filter_genes
toolshed:
  - toolshed
