# .shed.yml supporting automatic pushes.
owner: mvdbeek
name: r_goseq_1_22_0
description: goseq does selection-unbiased testing for category enrichment amongst differentially expressed (DE) genes for RNA-seq data
long_description: |
   Gene Ontology analyser. Does selection-unbiased testing for category enrichment amongst differentially expressed (DE) genes for RNA-seq data.
categories:
  - Statistics
  - RNA
  - Micro-array Analysis
homepage_url: https://bioconductor.org/packages/release/bioc/html/goseq.html
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/master/tools/goseq_1_22_0
toolshed:
  - testtoolshed
  - toolshed
