# .shed.yml supporting automatic pushes.
owner: mvdbeek
name: yac_clipperplanemotest7
description: Clips 3' adapters for small RNA sequencing reads.
long_description: |
  Clips 3' adapters for small RNA sequencing reads. Supports
  fasta and fastq output
categories:
  - RNA
  - Fastq Manipulation
homepage_url: http://drosophile.org/
remote_repository_url: https://bitbucket.org/drosofff/gedtools/
