# .shed.yml supporting automatic pushes.
owner: mvdbeek
name: patser
description: finds putative transcription factor binding sites 
long_description: |
  This program scores the L-mers (subsequences of length L) of the indicated sequences against the indicated alignment or weight matrix.
  The elements of an alignment matrix are simply the number of times that the indicated letter is observed at the indicated position of a sequence alignment.
  Such elements must be processed before the matrix can be used to score an L-mer (e.g., Hertz and Stormo, 1999, Bioinformatics, 15:563-577). 
  A weight matrix is a matrix whose elements are in a form considered appropriate for scoring an L-mer.
  Each element of an alignment matrix is converted to an element of a weight matrix by first adding pseudo-counts in proportion to the a priori probability of the 
  corresponding letter (see option "-b" in section 1 below) and dividing by the total number of sequences plus the total number of pseudo-counts. The resulting frequency
  is normalized by the a priori probability for the corresponding letter. The final quotient is converted to an element of a weight matrix by taking its natural logarithm. 
  The use of pseudo-counts here differs from previous versions of this program by being proportional to the a priori probability.
  Version 3 of this program differs from previous versions by also numerically estimating the p-value of the scores. The p-value calculated here is the probability of 
  observing a particular score or higher at a particular sequence position and does NOT account for the total amount of sequence being scored. P-values are estimated by 
  the method described in Staden, 1989, CABIOS, p. 89--96. The relative value for each element of the weight matrix is approximated by integers in a range determined by 
  the "-R" and "-M" options (section 6 below). The p-value is calculated for each possible integer score and the values are stored. The actual scores for the sequences 
  are determined from the true weight matrix. The true scores are converted to their corresponding integer values and their p-values are looked up.
  Matrices can be either horizontal or vertical. In a horizontal matrix, the columns correspond to the positions within the pattern, and the rows correspond to the letters.
  Each row begins with the corresponding letter (or integer, if the "-i" option is used). In a vertical matrix, the rows correspond to the positions within the pattern, 
  and the columns correspond to the letters. The first row contains the letters (or integers, if the "-i" option is used) corresponding to each column. In both types 
  of matrices, spaces, tabs, and vertical bars (|) are ignored. The output of the "consensus" and "wconsensus" programs consists of horizontal alignment matrices.
  The input files can contain comments according to the following convention. The portion of a line following a ';', '%', or '#' is considered a comment and is ignored. 
  Comments can begin anywhere in a line and always end at the end of the line. The output of this program is sent to the standard output.
categories:
  - Sequence Analysis
homepage_url: http://drosophile.org/
remote_repository_url: http://stormo.wustl.edu/resources.html
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
  - testtoolshed
