language: python
python: 2.7
install:
  - pip install click==5.1
  - pip install planemo

script:
  - planemo --version
  - planemo shed_lint --report_level warn --tools --fail_level error --recursive tools/
  - planemo shed_lint --report_level warn --tools --fail_level error --recursive packages/
  - planemo shed_lint --report_level warn --tools --fail_level error --recursive suites/
