# .shed.yml supporting automatic pushes.
owner: drosofff
name: msp_sr_size_histograms
description: Generates size histograms from small RNA bowtie alignments.
long_description: |
  Generates size histograms from small RNA bowtie alignments.
categories:
  - RNA
  - Graphics
  - Sequence Analysis
homepage_url: http://artbio.fr
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/master/tools/msp_sr_size_histograms
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
  - testtoolshed
  - toolshed
