# .shed.yml supporting automatic pushes.
owner: artbio
name: small_rna_map
description: Generate read count maps from alignment BAM files
long_description: |
  Generate read count maps from alignment BAM files, using pysam and r-lattice.
  In addition to the read counts (bars), median size, mean size and coverage of
  reads mapping at a any given position are plotted in the graphs.
  Takes sorted BAM files as inputs and produce pdf output  

categories:
  - RNA
  - SAM
  - Graphics
  - Next Gen Mappers

homepage_url: http://artbio.fr
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/master/tools/small_rna_map
toolshed:
  - testtoolshed
  - toolshed

