# .shed.yml supporting automatic pushes.
owner: drosofff
name: package_ged_velvet
description: velvet package
long_description: |
  velvet package
categories:
  - Tool Dependency Packages
homepage_url: http://drosophile.org/
remote_repository_url: https://bitbucket.org/drosofff/gedtools/
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
  - testtoolshed
