# .shed.yml supporting automatic pushes.
owner: drosofff
name: msp_cap3
description: cap3 wrapper
long_description: |
  cap3 wrapper.
  CAP3: A DNA sequence assembly program.
  Huang, X. and Madan, A. (1999) CAP3: A DNA sequence assembly program. Genome Res., 9, 868-877.
  http://seq.cs.iastate.edu/

categories:
  - Assembly
homepage_url: http://artbio.fr
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/master/tools/msp_cap3
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
  - testtoolshed
  - toolshed
