# .shed.yml supporting automatic pushes.
owner: chamaelj
name: basicplot
description: Graphics
long_description: |
  Graphics
categories:
  - Graphics
homepage_url: http://artbio.fr
remote_repository_url: https://github.com/chamaelj/tools-artbio/tree/master/tools/basicplot
toolshed:
- toolshed
- testtoolshed
