# .shed.yml supporting automatic pushes.
owner: chaimae_eljaouhari
name: basicplot
description: Graphics
long_description: |
  Take on tabular file of numerical data as input and produces pairwise plots of numerical data, in log-log scale.
categories:
  - Graphics
homepage_url: http://artbio.fr
remote_repository_url: https://github.com/chamaelj/tools-artbio/tree/master/tools/basicplot
toolshed:
- toolshed
- testtoolshed
