# .shed.yml supporting automatic pushes.
owner: drosofff
name: blast_to_scaffold
description: Generate DNA scaffold from blastn or tblastx alignments of Contigs
long_description: |
  This tool start from DNA contigs that aligned to a subject DNA sequence through blastn or tblastx.
  The contigs must be provided in fasta format. The blastn or tblastx output must be tabular, the 12 standard column plus column 13 with the length of the blastn or tblastx subject.
  The sequence used to BLAST (blastn or tblastx) the contigs must be provided to serve as a guide to the final assembly
  The final assembly is a DNA sequence.
  Nucleotides of the guide sequence which were not covered by contigs are in small letters in the output assembly.

categories:
  - RNA
  - Sequence Analysis
  - Assembly
homepage_url: http://artbio.fr
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/master/tools/blast_to_scaffold
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
  - testtoolshed
  - toolshed
