# .shed.yml supporting automatic pushes.
owner: artbio
name: filter_single_cell_expression_matrix
description: Filter out low quality cells and genes from raw scRNAseq expression matrix 
long_description: |
  Filter out low quality cells and genes from raw scRNAseq expression matrix using either scater or Seurat R package.
categories:
  - Transcriptomics
homepage_url: http://artbio.fr
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/master/tools/filter_single_cell_expression_matrix
toolshed:
  - toolshed
