# .shed.yml supporting automatic pushes.
owner: mvdbeek
name: deseq2
description: DESeq2 Profiling of readcount lists 
long_description: |
  DESeq2 Profiling of readcount lists. DESeq2 differential calling (order by padj, ascending). Still in development and testing.
  It is preferable to use the Differential_Count tool.
categories:
  - RNA
homepage_url: http://artbio.fr
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/master/tools/deseq2
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
