# .shed.yml supporting automatic pushes.
owner: artbio
name: pathifier
description: pathifier
long_description: |
  pathifier is a method to reduce dimension of dataset, cope with curse of dimensionality
  and find gene expression signatures in patient transcriptome data
categories:
  - Transcriptomics
  - Statistics # Check the category exists
homepage_url: https://
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/master/tools/pathifier
toolshed:
  - testtoolshed
  - toolshed
