# .shed.yml supporting automatic pushes.
owner: mvdbeek
name: package_ngs_1_1_3
description: NCBI ngs package
long_description: |
  NCBI ngs package. Required for NCBI sra toolkit package.
categories:
  - Tool Dependency Packages
homepage_url: 
remote_repository_url: 
