# .shed.yml supporting automatic pushes.
owner: artbio
name: concatenate_multiple_datasets
description: Concatenate multiple datasets tail-to-head, including collection datasets.
long_description: |
  Concatenate multiple datasets tail-to-head. Can reduce dataset collections to a single output file, with optionally names of the datasets as section headers.
categories:
  - Text Manipulation
homepage_url: http://artbio.fr
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/master/tools/concat_multi_datasets
toolshed:
  - toolshed
