# .shed.yml supporting automatic pushes.
owner: artbio
name: wisecondorx
description: WisecondorX
long_description: |
  Improved copy number detection for routine shallow whole-genome sequencing.
  See homepage URL for manual and code.
categories:
  - Variant Analysis
homepage_url: https://github.com/CenterForMedicalGeneticsGhent/WisecondorX/tree/master
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/master/tools/wisecondorx
toolshed:
  - toolshed
