# .shed.yml supporting automatic pushes.
owner: artbio
name: blast_unmatched
description: Extract unmatched query sequences from blast
long_description: |
  Extract unmatched query sequences that remained unmatched after blast
categories:
  - Fasta Manipulation
homepage_url: http://artbio.fr
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/main/tools/blast_unmatched
toolshed:
  - toolshed
