# .shed.yml supporting automatic pushes.
owner: mvdbeek
name: concatenate_multiple_datasets
description: Concatenate multiple datasets tail-to-head. Modification of the concatenate wrapper that comes with galaxy to replace the repeat section with multiple="True".
long_description: |
  Concatenate multiple datasets tail-to-head. Modification of the concatenate wrapper that comes with galaxy to replace the repeat section with multiple="True". Can reduce dataset collections to a single output file.
categories:
  - Text Manipulation
homepage_url: http://artbio.fr
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/master/tools/concatenate_multiple_datasets
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
  - testtoolshed
  - toolshed
