# .shed.yml supporting automatic pushes.
owner: artbio
name: fishertest
description: Fisher's exact test on two-column hit lists.
long_description: |
  Fisher's exact test on two-column hit lists.
categories:
  - RNA
  - Statistics
homepage_url: http://artbio.fr
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/main/tools/fisher_test
toolshed:
  - toolshed
