# .shed.yml supporting automatic pushes.
owner: fabiorjvieira
name: qrCoder
description: Generate qr codes images.
long_description: |
  Generate qr codes images.
categories:
  - Graphics
homepage_url: http://mississippi.snv.jussieu.fr/
remote_repository_url: https://github.com/fabiorjvieira/tools-artbio/tree/master/tools/qrCoder
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
  - testtoolshed
