# .shed.yml supporting automatic pushes.
owner: artbio
name: gsc_center_scale
description: Center or scale (standardize) data 
long_description: |
  Mean centers, standard deviation rescales, or does both operations on single cell
  transcriptomic data, or any type of numerical data
categories:
  - Transcriptomics
homepage_url: http://artbio.fr
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/master/tools/gsc_center_scale
toolshed:
  - toolshed
