# .shed.yml supporting automatic pushes.
owner: drosofff
name: msp_sr_bowtie
description: bowtie wrapper tool to align small RNA sequencing reads
long_description: |
  Bowtie wrapper tool to align small RNA sequencing reads. This tool belongs to the mississippi tool suite.
categories:
  - RNA
  - Next Gen Mappers
homepage_url: http://artbio.fr
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/master/tools/msp_sr_bowtie
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
  - testtoolshed
  - toolshed
