# .shed.yml supporting automatic pushes.
owner: drosofff
name: msp_sr_bowtie_cascade
description: Maps iteratively small RNA sequencing datasets to reference sequences.
long_description: |
  Maps iteratively small RNA sequencing datasets to reference sequences, in order to generate annotation of these datasets.
categories:
  - RNA
homepage_url: http://artbio.fr
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/master/tools/msp_sr_bowtie_cascade
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
  - testtoolshed
  - toolshed
