# .shed.yml supporting automatic pushes.
owner: artbio
name: small_rna_signatures
description: Computes the tendency of small RNAs to overlap with each other.
long_description: |
  Compute the tendency of small RNAs to overlap with each others for detailed information, 
  see C. Antoniewski, “Computing siRNA and piRNA Overlap Signatures.,” Methods Mol. Biol., vol. 1173, no. 12, pp. 135–146, 2014.
categories:
  - RNA
homepage_url: http://artbio.fr
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/master/tools/small_rna_signatures
toolshed:
  - toolshed
