# .shed.yml supporting automatic pushes.
owner: mvdbeek
name: package_sra_toolkit_2_5_2
description: NCBI sra_toolkit package
long_description: |
  NCBI sra_toolkit package.
categories:
  - Tool Dependency Packages
homepage_url: 
remote_repository_url: 
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/