# .shed.yml supporting automatic pushes.
owner: mvdbeek
name: package_sra_toolkit_2_5_2
description: NCBI sra_toolkit package
long_description: |
  NCBI sra_toolkit package.
categories:
  - Tool Dependency Packages
homepage_url: http://artbio.fr
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/master/packages/package_sra_toolkit_2_5_2
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
  - testtoolshed
  - toolshed
