owner: artbio
name: 
description: Filter variants in a Mutect2 VCF callset.
long_description: |
  FilterMutectCalls applies filters to the raw output of GATK4 Mutect2
  See https://gatk.broadinstitute.org/hc/en-us/articles/4409917406107-FilterMutectCalls
  for details.
categories:
  - Variant Analysis
homepage_url: http://artbio.fr
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/master/tools/filtermutectcalls
toolshed:
  - testtoolshed
  - toolshed
