# .shed.yml supporting automatic pushes.
owner: drosofff
name: yac_clipper
description: Clips 3' adapters for small RNA sequencing reads.
long_description: |
  Clips 3' adapters for small RNA sequencing reads. Supports
  fasta and fastq output
categories:
  - RNA
  - Fastq Manipulation
homepage_url: http://artbio.fr
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/master/tools/yac_clipper
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
  - testtoolshed
  - toolshed
