# .shed.yml supporting automatic pushes.
owner: artbio
name: justgzip
description: Compress fastq sequence files
long_description: |
  Returns the compressed gzip version of files using the multithreaded pigz program.
  accepted input formats include:
  - fastq
  - fastqsanger
  - fasta
  - paf
  - gff3
  - nii1
  - nii2
  - gii
  - tabular
  - txt
  - ...

categories:
  - Convert Formats
homepage_url: http://artbio.fr
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/main/tools/justgzip
toolshed:
  - https://toolshed.g2.bx.psu.edu/
