# .shed.yml supporting automatic pushes.
owner: drosofff
name: package_ged_oases
description: oases package
long_description: |
  oases package
categories:
  - Tool Dependency Packages
homepage_url: http://artbio.fr
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/master/packages/package_ged_velvet
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
  - testtoolshed
  - toolshed
