# .shed.yml supporting automatic pushes.
owner: drosofff
name: blastn_to_scaffold
description: Generate DNA scaffold from blastn alignment of Contigs
long_description: |
  This tool start from DNA contigs that aligned to a subject DNA sequence through blastn.
  The contigs must be provided in fasta format. The blastn output must be tabular, the 12 standard column plus column 13 with the length of the blastn subject.
  The final scaffold is a DNA sequence.
  Sequences of the subject DNA sequence which were not aligned to the contigs are replaced by Ns in this scaffold.

categories:
  - RNA
  - Sequence Analysis
  - Assembly
homepage_url: http://drosophile.org/
remote_repository_url: https://bitbucket.org/drosofff/gedtools/
