# .shed.yml supporting automatic pushes.
owner: drosofff
name: msp_oases
description: Short read assembler
long_description: |
  Oases use velvet to assemble sequence reads. Here the tool is used for short read assembly
categories:
  - Assembly
  - RNA
homepage_url: http://artbio.fr
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/master/tools/msp_oases
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
  - testtoolshed
  - toolshed
