# .shed.yml supporting automatic pushes.
owner: artbio
name: gsc-mannwhitney_de
description: Perform a differential expression analysis between the two groups of a signature score (high/low)
long_description:
categories:
  - Transcriptomics
homepage_url: http://artbio.fr
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/master/tools/gsc-mannwhitney_de
toolshed:
  - toolshed
