# .shed.yml supporting automatic pushes.
owner: mvdbeek
name: package_ncbi_vdb_2_5_2
description: NCBI VDB package
long_description: |
  NCBI VDB package. Required for NCBI sra toolkit package.
categories:
  - Tool Dependency Packages
homepage_url: http://artbio.fr
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/master/packages/package_ged_velvet
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
  - testtoolshed
  - toolshed
