# .shed.yml supporting automatic pushes.
owner: drosofff
name: msp_sr_bowtie_parser
description: Generates hit count lists from bowtie sequence read alignments.
long_description: |
  Generates hit count lists from bowtie sequence read alignments.
categories:
  - RNA
  - Transcriptomics
homepage_url: http://artbio.fr
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/master/tools/msp_sr_bowtie_parser
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
  - testtoolshed
  - toolshed
