# .shed.yml supporting automatic pushes.
owner: mvdbeek
name: package_mirdeep2
description: Contains a tool dependency definition that downloads and installs mirdeep2
long_description: |
  This dependency install mirdeep2.
categories:
  - Tool Dependency Packages
homepage_url: https://www.mdc-berlin.de/8551903/en/research/research_teams/systems_biology_of_gene_regulatory_elements/projects/miRDeep
remote_repository_url: https://bitbucket.org/drosofff/gedtools/
type: tool_dependency_definition
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
  - testtoolshed
