# .shed.yml supporting automatic pushes.
owner: mvdbeek
name: mississippi_toolsuite
description: Collection of mississippi tools for miRNA, siRNA and piRNA analysis.
long_description: |
  Collection of mississippi tools for miRNA, siRNA and piRNA analysis.
categories:
  - RNA
  - Sequence Analysis
  - Visualization
homepage_url: http://artbio.fr
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/master/suites/mississippi_toolsuite
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
  - testtoolshed
