# .shed.yml supporting automatic pushes.
owner: fabiorjvieira
name: qr_coder
description: Generate qr codes images.
long_description: |
  Generate qr codes images.
categories:
  - Graphics
homepage_url: https://github.com/ARTbio/
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/master/tools/qr_coder
toolshed:
  - http://134.157.182.55:9009/ 
