# .shed.yml supporting automatic pushes.
owner: fabiorjvieira
name: qr_coder
description: Generate qr codes images.
long_description: |
  Generate qr codes images.
categories:
  - Graphics
homepage_url: http://mississippi.snv.jussieu.fr/
remote_repository_url: https://github.com/fabiorjvieira/tools-artbio/tree/master/tools/qr_coder
toolshed:
  - https://localhost:9009
  - testtoolshed
