# .shed.yml supporting automatic pushes.
owner: mvdbeek
name: package_r_3_2_1_goseq_1_22_0
description: Contains a tool dependency definition that downloads and installs goseq.
long_description: |
   Contains a tool dependency definition that downloads and installs goseq.
   Gene Ontology analyser. Does selection-unbiased testing for category enrichment amongst differentially expressed (DE) genes for RNA-seq data.
categories:
  - Tool Dependency Packages
homepage_url: https://bioconductor.org/packages/release/bioc/html/goseq.html
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/master/packages/package_r_3_2_1_goseq_1_22_0
type: tool_dependency_definition
toolshed:
  - testtoolshed
  - toolshed
