# .shed.yml supporting automatic pushes.
owner: drosofff
name: sam_to_fastq
description: extract fastq reads from a SAM alignment file
long_description: |
  extract reads and their sequence quality from a SAM alignment file and returns a fastq file

categories:
  - Convert Formats
  - SAM

homepage_url: http://artbio.fr
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/master/tools/sam_to_fastq
toolshed:
  - testtoolshed
  - toolshed
