# .shed.yml supporting automatic pushes.
owner: artbio
name: cnv_facets
description: A suite of tools for FACETS allele-specific copy number analysis.
long_description: |
  This repository contains a suite of two tools to perform allele-specific copy
  number analysis using the FACETS algorithm.
  1. SNP Pileup for FACETS: Generates a SNP pileup file from Normal/Tumor BAMs.
  2. FACETS Analysis: Runs the core FACETS algorithm on the pileup file to call
  copy number alterations.
categories:
  - Variant Analysis
homepage_url: https://artbio.fr
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/main/tools/facets
toolshed:
  - toolshed
