# .shed.yml supporting automatic pushes.
owner: mvdbeek
name: package_ascp_3
description: package that downloads and installs the aspera connect client.
long_description: |
  package that downloads and installs the aspera connect client.
categories:
  - Tool Dependency Packages
homepage_url: http://artbio.fr
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/master/packages/package_ascp_3
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
  - testtoolshed
  - toolshed
