# .shed.yml supporting automatic pushes.
owner: drosofff
name: suite_visitor2
description: Collection of mississippi tools for virus detection or discovery from (small) RNA sequence datasets
long_description: |
  Collection of mississippi tools for virus detection or discovery from (small) RNA sequence datasets
categories:
  - RNA
  - Sequence Analysis
homepage_url: http://drosophile.org/
remote_repository_url: https://bitbucket.org/drosofff/gedtools/
