owner: artbio
name: artbio_mutect2
description: Find somatic variations
long_description: |
  MuTect2 is a somatic SNP and indel caller that combines the DREAM 
  challenge-winning somatic genotyping engine of the original MuTect
  with the assembly-based machinery of HaplotypeCaller.
  This wrapper mirrors the IUC wrapper
  https://github.com/galaxyproject/tools-iuc/blob/master/tools/gatk4/gatk4_Mutect2.xml.
  It allows analysing tumour samples with the help of available normal
  sample data. Appropriate code changes have been made in the original
  wrapper in order to expose this Mutect2 functionality.
categories:
  - Variant Analysis
homepage_url: http://artbio.fr
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/master/tools/artbio_mutect2
toolshed:
  - testtoolshed
  - toolshed
