owner: artbio
name: sambamba
description: downsample BAM/SAM or filter BAM/SAM on flags, fields, tags, and region
long_description: |
  This tools uses sambaba to downsample BAM/SAM or filter BAM/SAM
  on flags, fields, tags, and region 
categories:
  - SAM - Tools for manipulating alignments in the SAM format
homepage_url: http://artbio.fr
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/master/tools/sambamba
toolshed:
  - testtoolshed
  - toolshed
