# .shed.yml supporting automatic pushes.
owner: mvdbeek
name: package_ngs_sdk_1_1_3
description: NCBI ngs-sdk package
long_description: |
  NCBI ngs-sdk package. Required for NCBI sra toolkit package.
categories:
  - Tool Dependency Packages
homepage_url: 
remote_repository_url: 
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/