# .shed.yml supporting automatic pushes.
owner: mvdbeek
name: package_ngs_sdk_1_1_3
description: NCBI ngs-sdk package
long_description: |
  NCBI ngs-sdk package. Required for NCBI sra toolkit package.
categories:
  - Tool Dependency Packages
homepage_url: http://artbio.fr
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/master/packages/package_ngs_sdk_1_1_3
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
  - testtoolshed
  - toolshed
