categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles 1.4.1 version of Image python library.
long_description: |
  Image is a python library for image manipulation.
  https://github.com/francescortiz/images
name: package_image_1_4_1
owner: fabiorjvieira
homepage_url: https://github.com/ARTbio/
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/master/packages/package_image_1_4_1
type: tool_dependency_definition
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
  - testtoolshed
