# .shed.yml supporting automatic pushes.
owner: mvdbeek
name: deseq_with_replicates
description: DESeq 1 profiling with replicates.
long_description: |
  DESeq 1 profiling with replicates.
  For new projects use DESeq2.
categories:
  - RNA
homepage_url: http://bioconductor.org/packages/release/bioc/html/DESeq.html
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/master/tools/deseq1_with_replicates
toolshed:
  - https://lbcd41.snv.jussieu.fr/toolshed/
