# .shed.yml supporting automatic pushes.
owner: artbio
name: diff
description: Unix diff
long_description: |
  Returns the output of the unix diff command between two files.
categories:
  - Text Manipulation
homepage_url: http://artbio.fr
remote_repository_url: https://github.com/ARTbio/tools-artbio/tree/master/tools/diff
toolshed:
  - https://toolshed.g2.bx.psu.edu/
